## 전처리

#### 1. 데이터 불러오기

In [1]:
# 데이터 불러오기

import pandas as pd

df = pd.read_csv("news_dataset_2025.csv")

# 데이터 백업
df_raw = df.copy()

print("원본 데이터 개수:", len(df))

원본 데이터 개수: 600

#### 2. 중복 기사 제거

In [2]:
# 중복 기사 확인
df[df.duplicated(subset=['title','content'], keep=False)]

,title,content,date,press,url
13,자동차 개소세 30% 인하·소비 늘리면 추가 소득공제...효과 있을까?,상반기 소비 5% 이상 늘리면 20% 추가 소득공제 영세소상공인 점포 신용카드 금액...,2025-01-02 23:05:32,YTN,https://n.news.naver.com/mnews/article/052/000...
14,"올해 1.8% 저성장 전망...""필요시 추가 보강"" 추경 가능성도","한은 1.9%, IMF·KDI 2.0% 전망…""탄핵정국 미반영"" 정부, 상반기 67...",2025-01-02 23:04:21,YTN,https://n.news.naver.com/mnews/article/052/000...
21,피해 키운 로컬라이저 책임론 부상...음성 파일은 완성,[앵커] 제주항공 여객기 참사의 피해를 키운 원인으로 지목되는 로컬라이저 구조물의 ...,2025-01-02 22:31:48,YTN,https://n.news.naver.com/mnews/article/052/000...
41,트럼프 2기 출범…부산항 걱정·기대 교차,[KBS 부산] [앵커] 미국 트럼프 2기 정부가 이번 달 출범하면서 부산항도 격랑...,2025-01-02 22:04:15,KBS,https://n.news.naver.com/mnews/article/056/001...
55,“제2 판교”라더니…업무 용지 대폭 축소?,"[KBS 부산] [앵커] 이전을 앞둔 부산 도심 속 마지막 노른자위 땅, 범천동 철...",2025-01-02 22:03:06,KBS,https://n.news.naver.com/mnews/article/056/001...
58,경북도 “APEC 국회 사절단 파견해야”,[KBS 대구]경상북도가 APEC 정상회의 성공 개최를 위해 국회 사절단을 파견할 ...,2025-01-02 21:56:09,KBS,https://n.news.naver.com/mnews/article/056/001...
62,꽁꽁 얼어붙은 골목상권…소비진작 ‘안간힘’,[KBS 대구][앵커] 탄핵 정국과 제주항공 여객기 참사 등 어수선한 국내 상황에 ...,2025-01-02 21:45:56,KBS,https://n.news.naver.com/mnews/article/056/001...
63,충청북도 “실사구시 정신으로 민생 집중”,[KBS 청주] [앵커] 새해를 맞아 충청북도와 각 시·군의 핵심 현안을 살펴보는 ...,2025-01-02 21:44:38,KBS,https://n.news.naver.com/mnews/article/056/001...
66,[기록K] 제2공항 기본계획 고시…‘조류 충돌’ 최대 쟁점 전망,[KBS 제주] [앵커] 지난해 9월 제주 최대 현안인 제2공항 건설 사업 기본계획...,2025-01-02 21:47:14,KBS,https://n.news.naver.com/mnews/article/056/001...
69,노인 일자리는 진화 중,"[KBS 전주] [앵커] 초고령화 사회 속 일하는 노인, '실버워커'의 삶을 살펴보...",2025-01-02 21:46:54,KBS,https://n.news.naver.com/mnews/article/056/001...
70,"왕궁축산단지, 에덴 프로젝트 ‘청신호’","[KBS 전주]지난해 11월, 익산을 찾은 영국 에덴프로젝트팀이 왕궁 축산단지 답사...",2025-01-02 21:53:37,KBS,https://n.news.naver.com/mnews/article/056/001...
72,"“75살이 막내”…현실이 된 초고령 사회, 대책은?",[KBS 대전] [앵커] 인구 다섯 명 중 한 명은 65살을 넘어서며 우리나라가 초...,2025-01-02 21:54:03,KBS,https://n.news.naver.com/mnews/article/056/001...
73,‘풍어·안전 기원’ 초매식 열려,[KBS 대구][앵커] 올 한 해 풍어와 안전한 조업을 기원하는 초매식이 포항 구룡...,2025-01-02 21:44:01,KBS,https://n.news.naver.com/mnews/article/056/001...
77,"전북도, 내년 국가 예산 신규 사업 377개 발굴",[KBS 전주]전북도는 내년도 국가 예산 확보를 위해 5천3백억 원 규모의 신규 사...,2025-01-02 21:46:26,KBS,https://n.news.naver.com/mnews/article/056/001...
78,특별법 통과됐지만…“정부 재정지원이 최종 과제”,[KBS 대구][앵커] 탄핵 정국 속에서도 대구경북신공항 특별법 개정안이 국회 본회...,2025-01-02 21:45:21,KBS,https://n.news.naver.com/mnews/article/056/001...
95,‘어려운 시기’…경남도민 새해 바라는 것은?,"[KBS 창원] [앵커] 2025년 새해가 시작됐지만, 올해는 희망과 행복을 이야기...",2025-01-02 21:35:28,KBS,https://n.news.naver.com/mnews/article/056/001...
110,"올해 1.8% 저성장 전망...""필요시 추가 보강"" 추경 가능성도","한은 1.9%, IMF·KDI 2.0% 전망…""탄핵정국 미반영"" 정부, 상반기 67...",2025-01-02 20:53:40,YTN,https://n.news.naver.com/mnews/article/052/000...
118,자동차 개소세 30% 인하·소비 늘리면 추가 소득공제...효과 있을까?,상반기 소비 5% 이상 늘리면 20% 추가 소득공제 영세소상공인 점포 신용카드 금액...,2025-01-02 20:53:53,YTN,https://n.news.naver.com/mnews/article/052/000...
154,"왕궁축산단지, 에덴 프로젝트 ‘청신호’","[KBS 전주]지난해 11월, 익산을 찾은 영국 에덴프로젝트팀이 왕궁 축산단지 답사...",2025-01-02 19:53:55,KBS,https://n.news.naver.com/mnews/article/056/001...
161,충청북도 “실사구시 정신으로 민생 집중”,[KBS 청주] [앵커] 새해를 맞아 충청북도와 각 시·군의 핵심 현안을 살펴보는 ...,2025-01-02 19:41:14,KBS,https://n.news.naver.com/mnews/article/056/001...
164,경북도 “APEC 국회 사절단 파견해야”,[KBS 대구]경상북도가 APEC 정상회의 성공 개최를 위해 국회 사절단을 파견할 ...,2025-01-02 19:44:23,KBS,https://n.news.naver.com/mnews/article/056/001...
172,트럼프 2기 출범…부산항 걱정·기대 교차,[KBS 부산] [앵커] 미국 트럼프 2기 정부가 이번 달 출범하면서 부산항도 격랑...,2025-01-02 19:47:08,KBS,https://n.news.naver.com/mnews/article/056/001...
185,노인 일자리는 진화 중,"[KBS 전주] [앵커] 초고령화 사회 속 일하는 노인, '실버워커'의 삶을 살펴보...",2025-01-02 19:34:08,KBS,https://n.news.naver.com/mnews/article/056/001...
192,"“75살이 막내”…현실이 된 초고령 사회, 대책은?",[KBS 대전] [앵커] 인구 다섯 명 중 한 명은 65살을 넘어서며 우리나라가 초...,2025-01-02 19:35:24,KBS,https://n.news.naver.com/mnews/article/056/001...
195,특별법 통과됐지만…“정부 재정지원이 최종 과제”,[KBS 대구][앵커] 탄핵 정국 속에서도 대구경북신공항 특별법 개정안이 국회 본회...,2025-01-02 19:41:01,KBS,https://n.news.naver.com/mnews/article/056/001...
211,“제2 판교”라더니…업무 용지 대폭 축소?,"[KBS 부산] [앵커] 이전을 앞둔 부산 도심 속 마지막 노른자위 땅, 범천동 철...",2025-01-02 19:29:03,KBS,https://n.news.naver.com/mnews/article/056/001...
213,피해 키운 로컬라이저 책임론 부상...음성 파일은 완성,[앵커] 제주항공 여객기 참사의 피해를 키운 원인으로 지목되는 로컬라이저 구조물의 ...,2025-01-02 19:23:14,YTN,https://n.news.naver.com/mnews/article/052/000...
217,"전북도, 내년 국가 예산 신규 사업 377개 발굴",[KBS 전주]전북도는 내년도 국가 예산 확보를 위해 5천3백억 원 규모의 신규 사...,2025-01-02 19:33:53,KBS,https://n.news.naver.com/mnews/article/056/001...
220,‘어려운 시기’…경남도민 새해 바라는 것은?,"[KBS 창원] [앵커] 2025년 새해가 시작됐지만, 올해는 희망과 행복을 이야기...",2025-01-02 19:15:45,KBS,https://n.news.naver.com/mnews/article/056/001...
221,[기록K] 제2공항 기본계획 고시…‘조류 충돌’ 최대 쟁점 전망,[KBS 제주] [앵커] 지난해 9월 제주 최대 현안인 제2공항 건설 사업 기본계획...,2025-01-02 19:19:57,KBS,https://n.news.naver.com/mnews/article/056/001...
227,‘풍어·안전 기원’ 초매식 열려,[KBS 대구][앵커] 올 한 해 풍어와 안전한 조업을 기원하는 초매식이 포항 구룡...,2025-01-02 19:10:28,KBS,https://n.news.naver.com/mnews/article/056/001...
235,꽁꽁 얼어붙은 골목상권…소비진작 ‘안간힘’,[KBS 대구][앵커] 탄핵 정국과 제주항공 여객기 참사 등 어수선한 국내 상황에 ...,2025-01-02 19:15:16,KBS,https://n.news.naver.com/mnews/article/056/001...
270,헌화 기다리는 어린이들,(무안=연합뉴스) 조남수 기자 = 2일 전남 무안군 무안국제공항에 마련된 제주항공 ...,2025-01-02 18:50:22,연합뉴스,https://n.news.naver.com/mnews/article/001/001...
271,헌화 기다리는 어린이들,(무안=연합뉴스) 조남수 기자 = 2일 전남 무안군 무안국제공항에 마련된 제주항공 ...,2025-01-02 18:50:17,연합뉴스,https://n.news.naver.com/mnews/article/001/001...
272,헌화 기다리는 어린이들,(무안=연합뉴스) 조남수 기자 = 2일 전남 무안군 무안국제공항에 마련된 제주항공 ...,2025-01-02 18:51:08,연합뉴스,https://n.news.naver.com/mnews/article/001/001...
289,유가족 질문 듣는 박상우 장관과 나원오 수사본부장,(무안=연합뉴스) 조남수 기자 = 박상우 국토교통부 장관과 나원오 전남경찰청 수사본...,2025-01-02 18:45:01,연합뉴스,https://n.news.naver.com/mnews/article/001/001...
296,유가족 질문 듣는 박상우 장관과 나원오 수사본부장,(무안=연합뉴스) 조남수 기자 = 박상우 국토교통부 장관과 나원오 전남경찰청 수사본...,2025-01-02 18:45:14,연합뉴스,https://n.news.naver.com/mnews/article/001/001...

In [3]:
# 중복 기사 제거 (같은 기사 중 최신 기사만 유지)
# 1.날짜 형식 변환
df['date'] = pd.to_datetime(df['date'])

# 2.title + content 기준 중복 제거
df = df.sort_values("date").drop_duplicates(subset=['title','content'], keep="last")

# 백업
df_deduplicated = df.copy()

print("중복 제거 후:", len(df))

중복 제거 후: 581

#### 3. 언론사별 기사 개수 확인 및 기사가 13개 이상인 언론사만 필터링

In [4]:
# 언론사별 기사 개수 확인
df['press'].value_counts()

press
파이낸셜뉴스      55
KBS         52
한국경제        46
매일경제        33
이데일리        32
SBS Biz     29
부산일보        26
연합뉴스        22
서울경제        17
국제신문        13
세계일보        13
머니투데이       13
국민일보        12
아이뉴스24      12
한국일보        12
TV조선        10
연합뉴스TV      10
조선일보        10
경향신문         9
데일리안         9
이코노미스트       9
뉴시스          9
아시아경제        9
디지털타임스       8
한겨레          8
매일신문         8
매경이코노미       7
한경비즈니스       7
YTN          7
서울신문         6
코리아중앙데일리     6
MBC          6
MBN          6
문화일보         5
더팩트          5
뉴스1          4
헤럴드경제        4
한국경제TV       3
동아일보         3
SBS          3
조세일보         3
JTBC         3
대전일보         3
채널A          2
조선비즈         2
중앙일보         2
일간스포츠        1
동행미디어 시대     1
경기일보         1
전자신문         1
강원도민일보       1
강원일보         1
스포츠경향        1
노컷뉴스         1
Name: count, dtype: int64

In [5]:
# 기사 13개 이상인 언론사만 필터링

press_counts = df['press'].value_counts()

valid_press = press_counts[press_counts >= 13].index

df = df[df['press'].isin(valid_press)]

# 백업
df_press_filtered = df.copy()

print("언론사 필터링 후:", len(df))
print("남은 언론사 수:", df['press'].nunique())

언론사 필터링 후: 351
남은 언론사 수: 12

#### 4. 제목과 본문 결합

In [6]:
# 제목 + 본문 결합

df['text'] = df['title'].fillna('') + " " + df['content'].fillna('')

# 백업
df_text_combined = df.copy()

#### 5. 텍스트 정제

In [7]:
# 텍스트 정제(특수문자 / HTML / 이메일 / URL 제거)
import re

def clean_text(text):

    text = re.sub(r'<.*?>', ' ', text)           # html 태그 제거
    text = re.sub(r'http\S+|www\S+', ' ', text)  # url 제거
    text = re.sub(r'\S+@\S+', ' ', text)         # 이메일 제거
    text = re.sub(r'[^가-힣\s]', ' ', text)      # 특수문자 제거
    text = re.sub(r'\s+', ' ', text)             # 공백 정리

    return text.strip()


df['clean_text'] = df['text'].apply(clean_text)

# 백업
df_text_cleaned = df.copy()

In [8]:
!pip install kiwipiepy

Requirement already satisfied: kiwipiepy in c:\users\songa\appdata\local\programs\python\python311\lib\site-packages (0.22.2)
Requirement already satisfied: kiwipiepy_model<0.23,>=0.22 in c:\users\songa\appdata\local\programs\python\python311\lib\site-packages (from kiwipiepy) (0.22.1)
Requirement already satisfied: numpy in c:\users\songa\appdata\local\programs\python\python311\lib\site-packages (from kiwipiepy) (2.2.6)
Requirement already satisfied: tqdm in c:\users\songa\appdata\local\programs\python\python311\lib\site-packages (from kiwipiepy) (4.67.1)
Requirement already satisfied: colorama in c:\users\songa\appdata\local\programs\python\python311\lib\site-packages (from tqdm->kiwipiepy) (0.4.6)

WARNING: Ignoring invalid distribution ~ympy (C:\Users\songa\AppData\Local\Programs\Python\Python311\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ympy (C:\Users\songa\AppData\Local\Programs\Python\Python311\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ympy (C:\Users\songa\AppData\Local\Programs\Python\Python311\Lib\site-packages)

[notice] A new release of pip is available: 25.0.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

#### 6. 형태소 분석(명사+동사+형용사)

In [9]:
# 형태소 분석(명사 + 동사 + 형용사)
from kiwipiepy import Kiwi

kiwi = Kiwi()
target_pos = ["NNG", "NNP", "VV", "VA"]

def tokenize(text):

    tokens = []

    result = kiwi.analyze(text)[0][0]

    for token, pos, _, _ in result:
        if pos in target_pos:
            tokens.append(token)

    return tokens

df["tokens"] = df["clean_text"].apply(tokenize)

df_tokenized = df.copy()

#### 7. 불용어 제거

In [10]:
# 불용어 제거

stopwords = ['기자','사진','뉴스','연합뉴스','뉴시스','보도','관련','이번','대한','통해', '하다', '이다',
'지난','현재','이날','오전','오후','당시','이후','앞서','최근','정부','관계자','업계','측','대통령','국회','위원회',
'등','것','수','때','위해','경우','때문','대해','지난해','올해','내년', '년','월','일','억','만','천''파이낸셜뉴스',
'KBS','한국경제','매일경제','이데일리','SBS Biz','부산일보','연합뉴스','서울경제','머니투데이','세계일보','국제신문'
]

def remove_stopwords(tokens):
    
    return [t for t in tokens if t not in stopwords]

df['tokens'] = df['tokens'].apply(remove_stopwords)

df_stopwords_removed = df.copy()

In [14]:
df = df_stopwords_removed.copy()

In [15]:
# 추가적인 불용어 제거

stopwords = [
'가능','상황','수준','계획','내용','포함','실제','방안','검토','일각','입장','경우','관련','통해',

# 뉴스 문체 단어
'발표','조사','응답','보고','설명','강조','언급','진단','요청','건의',

# 일반 서술 단어
'전체','가운데','이전','이후','처음','주요','전반','핵심','본격','적극','철저',

# 추상적인 단어
'효과','역할','문제','요소','체계','기반','구성','구축','확보','강화','지원',

# 시간 표현
'작년','새해','연내','시기','기간','차례',

# 분석에 의미 약한 동사
'나타나','밝히','따르','보이','점치','내다보','늘리','줄이','높이','갖추','만들',

# 문맥 보조 단어
'대상','이용','통하','위하','대하'
]

df['tokens'] = df['tokens'].apply(remove_stopwords)
df_stopwords_removed2 = df.copy()

#### 8. 한 글자 토큰 및 숫자 토큰 제거

In [16]:
# 한 글자인 토큰 제거

def remove_single_char(tokens):

    return [t for t in tokens if len(t) > 1]


df['tokens'] = df['tokens'].apply(remove_single_char)

# 백업
df_single_removed = df.copy()

# 숫자 토큰 제거

def remove_numbers(tokens):

    return [t for t in tokens if not t.isdigit()]


df['tokens'] = df['tokens'].apply(remove_numbers)

# 최종 전처리 백업
df_preprocessed = df.copy()

print("최종 데이터 개수:", len(df_preprocessed))

최종 데이터 개수: 351

#### 9. 최종 전처리 데이터 저장

In [17]:
# 최종 전처리 데이터 저장

df_preprocessed.to_csv("news_preprocessed_2025.csv", index=False)

#### 10. 최종 데이터 확인

In [19]:
# 데이터 확인
df = df.reset_index(drop=True)
df

,title,content,date,press,url,text,clean_text,tokens
0,경기 침체에 금리 인하 가능성…하반기 대출 규제 더 세진다,[2025 금융시장 대전망] <1>깐깐해지는 가계빚 관리 가계대출 증가 한도 70조...,2025-01-02 17:56:27,서울경제,https://n.news.naver.com/mnews/article/011/000...,경기 침체에 금리 인하 가능성…하반기 대출 규제 더 세진다 [2025 금융시장 대전...,경기 침체에 금리 인하 가능성 하반기 대출 규제 더 세진다 금융시장 대전망 깐깐해지...,"[경기, 침체, 금리, 인하, 하반기, 대출, 규제, 금융, 시장, 전망, 가계, ..."
1,중기부에 AI전담 TF생긴다,AI생산적용 中企 1.5%그쳐 제조현장 AI 활성화 돕고 스마트제조기업 육성 취지 ...,2025-01-02 17:58:11,매일경제,https://n.news.naver.com/mnews/article/009/000...,중기부에 AI전담 TF생긴다 AI생산적용 中企 1.5%그쳐 제조현장 AI 활성화 돕...,중기부에 전담 생긴다 생산적용 그쳐 제조현장 활성화 돕고 스마트제조기업 육성 취지 ...,"[중기, 전담, 생기, 생산, 적용, 그치, 제조, 현장, 활성, 스마트, 제조, ..."
2,"현대차그룹 전기차 5종, 美서 전기차 보조금 받는다",현대차 아이오닉 9·기아 EV9 등 현지 EV 생산 본격화…IRA 수혜 '트럼프 2...,2025-01-02 17:58:14,이데일리,https://n.news.naver.com/mnews/article/018/000...,"현대차그룹 전기차 5종, 美서 전기차 보조금 받는다 현대차 아이오닉 9·기아 EV9...",현대차그룹 전기차 종 서 전기차 보조금 받는다 현대차 아이오닉 기아 등 현지 생산 ...,"[현대차그룹, 전기, 전기, 보조금, 현대차, 아이오닉, 기아, 현지, 생산, 수혜..."
3,"4대금융 ""견고한 신뢰 쌓아 위기 넘겠다""","주요 금융그룹, 비상경영 선언 회장들, 신년사서 일제히 ""위기"" 불확실성에 신뢰 구...",2025-01-02 17:58:21,한국경제,https://n.news.naver.com/mnews/article/015/000...,"4대금융 ""견고한 신뢰 쌓아 위기 넘겠다"" 주요 금융그룹, 비상경영 선언 회장들, ...",대금융 견고한 신뢰 쌓아 위기 넘겠다 주요 금융그룹 비상경영 선언 회장들 신년사서 ...,"[금융, 신뢰, 위기, 금융, 그룹, 비상, 경영, 선언, 회장, 신년사, 위기, ..."
4,"김영록 전남지사, 여객기 사고 피해지원 특별법 제정 건의",(무안=연합뉴스) 형민우 기자 = 김영록 전남지사는 2일 무안국제공항 분향소를 찾은...,2025-01-02 17:58:54,연합뉴스,https://n.news.naver.com/mnews/article/001/001...,"김영록 전남지사, 여객기 사고 피해지원 특별법 제정 건의 (무안=연합뉴스) 형민우 ...",김영록 전남지사 여객기 사고 피해지원 특별법 제정 건의 무안 연합뉴스 형민우 기자 ...,"[김영록, 전남, 지사, 여객기, 사고, 피해, 특별법, 제정, 무안, 김영록, 전..."
...,...,...,...,...,...,...,...,...
346,"‘상반기에 올인’ 조기집행 총력, 1월부터 푼다",[앵커] 올해 한국의 경제 성장률이 1.8%에 그칠 것으로 전망됐습니다. 2년 만에...,2025-01-02 23:16:06,KBS,https://n.news.naver.com/mnews/article/056/001...,"‘상반기에 올인’ 조기집행 총력, 1월부터 푼다 [앵커] 올해 한국의 경제 성장률이...",상반기에 올인 조기집행 총력 월부터 푼다 앵커 올해 한국의 경제 성장률이 에 그칠 ...,"[상반기, 올인, 조기, 집행, 총력, 앵커, 한국, 경제, 성장, 그치, 전망, ..."
347,노르웨이 작년 신차 90%가 전기차…올해 100% 목표,테슬라 압도적 1위속 中 제조사들 점유율 10% 돌파 (브뤼셀=연합뉴스) 정빛나 특...,2025-01-02 23:21:36,연합뉴스,https://n.news.naver.com/mnews/article/001/001...,노르웨이 작년 신차 90%가 전기차…올해 100% 목표 테슬라 압도적 1위속 中 제...,노르웨이 작년 신차 가 전기차 올해 목표 테슬라 압도적 위속 제조사들 점유율 돌파 ...,"[노르웨이, 신차, 전기, 목표, 테슬라, 압도, 위속, 제조사, 점유, 돌파, 브..."
348,전세보증금 5.7억 안 돌려준 19세도… '악성 임대인' 1177명 명단 공개,"안심전세포털에 이름·신상 공개 평균 47세, 1인당 16.1억 미반환 [서울경제] ...",2025-01-02 23:31:12,서울경제,https://n.news.naver.com/mnews/article/011/000...,전세보증금 5.7억 안 돌려준 19세도… '악성 임대인' 1177명 명단 공개 안심...,전세보증금 억 안 돌려준 세도 악성 임대인 명 명단 공개 안심전세포털에 이름 신상 ...,"[전세, 보증금, 돌리, 악성, 임대인, 명단, 공개, 안심, 전세, 포털, 이름,..."
349,테슬라 지난해 차량인도량 179만대…전년대비 감소,작년 4분기 차량인도 49만5천대…시장기대 밑돌아 (뉴욕=연합뉴스) 이지헌 특파원 ...,2025-01-02 23:33:51,연합뉴스,https://n.news.naver.com/mnews/article/001/001...,테슬라 지난해 차량인도량 179만대…전년대비 감소 작년 4분기 차량인도 49만5천대...,테슬라 지난해 차량인도량 만대 전년대비 감소 작년 분기 차량인도 만 천대 시장기대 ...,"[테슬라, 차량, 인도, 전년, 대비, 감소, 분기, 차량, 인도, 시장, 기대, ..."
350,"우리은행, 10년 이상 대상 희망퇴직..""최대 31개월치""",우리은행이 1969년생 이후 직원들 대상으로 희망퇴직을 시행합니다. 오늘(2일) 금...,2025-01-02 23:54:13,SBS Biz,https://n.news.naver.com/mnews/article/374/000...,"우리은행, 10년 이상 대상 희망퇴직..""최대 31개월치"" 우리은행이 1969년생 ...",우리은행 년 이상 대상 희망퇴직 최대 개월치 우리은행이 년생 이후 직원들 대상으로 ...,"[우리은행, 이상, 희망퇴직, 최대, 은행, 직원, 희망퇴직, 시행, 금융, 우리은..."